services:
  - type: web
    name: portfolio-server
    runtime: node
    plan: free
    buildCommand: "npm install --legacy-peer-deps"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MY_EMAIL
        sync: false
